apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          # Use your ACR image/tag here
          image: sit722acr.azurecr.io/order_service:testing-latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8001
          env:
            # --- Postgres connection ---
            - name: POSTGRES_HOST
              value: order-db
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: ecomm-config-sit722
                  key: ORDERS_DB_NAME
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: ecomm-secrets-sit722
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ecomm-secrets-sit722
                  key: POSTGRES_PASSWORD

            # --- RabbitMQ connection ---
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: ecomm-config-sit722
                  key: RABBITMQ_HOST
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: ecomm-secrets-sit722
                  key: RABBITMQ_USER
            - name: RABBITMQ_PASS
              valueFrom:
                secretKeyRef:
                  name: ecomm-secrets-sit722
                  key: RABBITMQ_PASS

            # --- Internal service URLs (from ConfigMap) ---
            - name: PRODUCT_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: ecomm-config-sit722
                  key: PRODUCT_SERVICE_URL
            - name: CUSTOMER_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: ecomm-config-sit722
                  key: CUSTOMER_SERVICE_URL
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  selector:
    app: order-service
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
  type: ClusterIP
