apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: sit722
  labels:
    app: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: sit722acr.azurecr.io/product_service:testing-latest
          ports:
            - containerPort: 8002   # ✅ Fixed
          env:
            - name: POSTGRES_HOST
              value: product-db
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: ecomm-config-sit722
                  key: PRODUCTS_DB_NAME
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: ecomm-secrets-sit722
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ecomm-secrets-sit722
                  key: POSTGRES_PASSWORD
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: ecomm-config-sit722
                  key: RABBITMQ_HOST
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: ecomm-secrets-sit722
                  key: RABBITMQ_USER
            - name: RABBITMQ_PASS
              valueFrom:
                secretKeyRef:
                  name: ecomm-secrets-sit722
                  key: RABBITMQ_PASS

---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: sit722
spec:
  type: LoadBalancer
  selector:
    app: product-service
  ports:
    - port: 8000        # what clients use externally
      targetPort: 8002  # ✅ matches containerPort
