# k8s/secrets.yaml

apiVersion: v1
kind: Secret
metadata:
  name: ecomm-secrets-sit722
  namespace: sit722
type: Opaque
data:
  # PostgreSQL credentials (used by all DB deployments)
  POSTGRES_USER: "cG9zdGdyZXM="       # base64 for 'postgres'
  POSTGRES_PASSWORD: "cG9zdGdyZXM="   # base64 for 'postgres'

  # RabbitMQ credentials
  RABBITMQ_USER: "Z3Vlc3Q="           # base64 for 'guest'
  RABBITMQ_PASS: "Z3Vlc3Q="           # base64 for 'guest'

  # Azure Storage Account credentials for product-service uploads
  # Replace with your own base64 encoded values
  # Mac/Linux: echo -n 'myazurestorageaccount' | base64
  # Windows (PowerShell): [Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes("myazurestorageaccount"))
  AZURE_STORAGE_ACCOUNT_NAME: ""
  AZURE_STORAGE_ACCOUNT_KEY: ""
