name: CI (testing) - Test, Build, Push to ACR

on:
  push:
    branches: [ "testing" ]

env:
  ACR: ${{ secrets.ACR_LOGIN_SERVER }}   # e.g., sit722acr.azurecr.io

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - backend/customer_service
          - backend/order_service
          - backend/product_service
          - frontend
    steps:
      - uses: actions/checkout@v4

      # Python tests for backend services (skip for frontend)
      - name: Setup Python
        if: startsWith(matrix.service, 'backend/')
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps & run tests
        if: startsWith(matrix.service, 'backend/')
        working-directory: ${{ matrix.service }}
        run: |
          python -m pip install -U pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f tests/test_main.py ]; then pytest -q; else echo "No tests found, skipping"; fi

      - name: Frontend quick check
        if: matrix.service == 'frontend'
        run: echo "No tests for frontend; continuing."

  build_and_push:
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - path: backend/customer_service
            image: customer_service
          - path: backend/order_service
            image: order_service
          - path: backend/product_service
            image: product_service
          - path: frontend
            image: frontend
    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Login to ACR using AAD (derive registry name from login server inside the shell)
      - name: az acr login
        run: |
          ACR_NAME="$(echo "${{ env.ACR }}" | cut -d'.' -f1)"   # sit722acr.azurecr.io -> sit722acr
          az acr login --name "$ACR_NAME"

      - name: Build & Push ${{ matrix.image }}
        run: |
          IMAGE="${{ env.ACR }}/${{ matrix.image }}"
          TAG_SHA="testing-${{ github.sha }}"
          TAG_LATEST="testing-latest"
          docker build -t "$IMAGE:$TAG_SHA" -t "$IMAGE:$TAG_LATEST" "${{ matrix.path }}"
          docker push "$IMAGE:$TAG_SHA"
          docker push "$IMAGE:$TAG_LATEST"
