name: Deploy to AKS

on:
  # Manual trigger (recommended for Stage 2)
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to deploy"
        required: true
        default: "testing"
      namespace:
        description: "Kubernetes namespace"
        required: true
        default: "sit722"

env:
  # 👇 change if your RG/AKS names are different
  RG: rg-sit722
  AKS: aks-sit722

jobs:
  deploy:
    runs-on: ubuntu-latest

    # Needed for Azure OIDC and repo checkout
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS context
        uses: azure/aks-set-context@v4
        with:
          resource-group: ${{ env.RG }}
          cluster-name:   ${{ env.AKS }}

      - name: Set env (namespace)
        run: echo "NAMESPACE=${{ github.event.inputs.namespace }}" >> "$GITHUB_ENV"

      - name: Apply ALL manifests (idempotent)
        run: |
          set -euo pipefail
          kubectl apply -f k8s/namespace.yaml
          kubectl -n "$NAMESPACE" apply -f k8s/secrets.yaml
          kubectl -n "$NAMESPACE" apply -f k8s/configmaps.yaml
          kubectl -n "$NAMESPACE" apply -f k8s/rabbitmq.yaml
          kubectl -n "$NAMESPACE" apply -f k8s/customer-db.yaml
          kubectl -n "$NAMESPACE" apply -f k8s/product-db.yaml
          kubectl -n "$NAMESPACE" apply -f k8s/order-db.yaml
          kubectl -n "$NAMESPACE" apply -f k8s/customer-service.yaml
          kubectl -n "$NAMESPACE" apply -f k8s/product-service.yaml
          kubectl -n "$NAMESPACE" apply -f k8s/order-service.yaml
          kubectl -n "$NAMESPACE" apply -f k8s/nginx-config.yaml
          kubectl -n "$NAMESPACE" apply -f k8s/frontend.yaml

      - name: Show what exists (deployments/pods/services)
        run: |
          kubectl -n "$NAMESPACE" get deploy,po,svc -o wide || true

      - name: Wait for deployments to be Ready
        run: |
          set -e
          # App-facing deployments (use label app=<name> if present; else name)
          APPS=("frontend" "customer-service" "product-service" "order-service")
          for app in "${APPS[@]}"; do
            echo "==> Waiting for app=$app (if present)"
            if kubectl -n "$NAMESPACE" get deploy -l app="$app" --no-headers 2>/dev/null | grep -q .; then
              kubectl -n "$NAMESPACE" rollout status deploy -l app="$app" --timeout=300s
            elif kubectl -n "$NAMESPACE" get deploy "$app" --ignore-not-found -o name | grep -q .; then
              kubectl -n "$NAMESPACE" rollout status deploy/"$app" --timeout=300s
            else
              echo "Skip: no deployment found for $app"
            fi
          done

          # Infra deployments (names may differ repo-to-repo; wait only if they exist)
          OTHERS=("customer-db-deployment" "product-db" "order-db" "rabbitmq")
          for d in "${OTHERS[@]}"; do
            if kubectl -n "$NAMESPACE" get deploy "$d" --ignore-not-found -o name | grep -q .; then
              echo "==> Waiting for $d"
              kubectl -n "$NAMESPACE" rollout status deploy/"$d" --timeout=300s
            else
              echo "Skip: deployment/$d not found (ok)"
            fi
          done

      - name: Wait for LoadBalancer EXTERNAL-IPs
        run: |
          set -e
          SVCS=("frontend" "customer-service" "product-service" "order-service")
          for s in "${SVCS[@]}"; do
            echo "Waiting for EXTERNAL-IP on service/$s ..."
            for i in {1..40}; do
              IP=$(kubectl -n "$NAMESPACE" get svc "$s" -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
              HOST=$(kubectl -n "$NAMESPACE" get svc "$s" -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
              if [ -n "$IP" ] || [ -n "$HOST" ]; then
                echo "::notice title=$s EXTERNAL-IP::${IP:-$HOST}"
                break
              fi
              sleep 15
            done
          done

      - name: Show services (IPs)
        run: kubectl get svc -n "$NAMESPACE" -o wide
