name: Deploy to AKS

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to deploy"
        required: true
        default: "testing"
      namespace:
        description: "Kubernetes namespace"
        required: true
        default: "sit722"
  push:
    branches: ["testing"]
    paths:
      - "k8s/**"
      - ".github/workflows/deploy-to-aks.yml"

env:
  # 👇 change if your RG/AKS names are different
  RG: rg-sit722
  AKS: aks-sit722

jobs:
  deploy:
    runs-on: ubuntu-latest

    # Needed for Azure OIDC and repo checkout
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS context
        uses: azure/aks-set-context@v4
        with:
          resource-group: ${{ env.RG }}
          cluster-name:   ${{ env.AKS }}

      - name: Set env (namespace)
        run: echo "NAMESPACE=${{ github.event.inputs.namespace }}" >> "$GITHUB_ENV"

      - name: Apply ALL manifests (idempotent)
        run: |
          set -euo pipefail
          kubectl apply -f k8s/namespace.yaml
          kubectl -n "$NAMESPACE" apply -f k8s/secrets.yaml
          kubectl -n "$NAMESPACE" apply -f k8s/configmaps.yaml
          kubectl -n "$NAMESPACE" apply -f k8s/rabbitmq.yaml
          kubectl -n "$NAMESPACE" apply -f k8s/customer-db.yaml
          kubectl -n "$NAMESPACE" apply -f k8s/product-db.yaml
          kubectl -n "$NAMESPACE" apply -f k8s/order-db.yaml
          kubectl -n "$NAMESPACE" apply -f k8s/customer-service.yaml
          kubectl -n "$NAMESPACE" apply -f k8s/product-service.yaml
          kubectl -n "$NAMESPACE" apply -f k8s/order-service.yaml
          kubectl -n "$NAMESPACE" apply -f k8s/nginx-config.yaml
          kubectl -n "$NAMESPACE" apply -f k8s/frontend.yaml

      - name: Show what exists (deployments/pods/services)
        run: |
          kubectl -n "$NAMESPACE" get deploy,po,svc -o wide || true

            - name: Wait for deployments (non-fatal, with diagnostics)
        run: |
          set -u
          APPS=("frontend" "frontend-deployment" "customer-service" "order-service" "product-service")

          for name in "${APPS[@]}"; do
            echo "==> Checking deployment: $name"
            if ! kubectl -n "$NAMESPACE" get deploy "$name" --ignore-not-found -o name | grep -q .; then
              echo "Skip: deployment/$name not found"
              continue
            fi

            echo "Waiting for deployment/$name rollout (10m timeout)..."
            if ! kubectl -n "$NAMESPACE" rollout status deploy/"$name" --timeout=600s; then
              echo "!! Rollout did not complete for $name — collecting diagnostics (continuing)"
              kubectl -n "$NAMESPACE" describe deploy "$name" || true
              kubectl -n "$NAMESPACE" get pods -l app="$name" -o wide || true
              POD=$(kubectl -n "$NAMESPACE" get pods -l app="$name" -o jsonpath='{.items[0].metadata.name}' 2>/dev/null || true)
              if [ -n "$POD" ]; then
                kubectl -n "$NAMESPACE" describe pod "$POD" || true
                kubectl -n "$NAMESPACE" logs "$POD" --tail=200 || true
              fi
            fi
          done

      - name: Wait for LoadBalancer EXTERNAL-IPs
        run: |
          set -e
          SVCS=("frontend" "customer-service" "product-service" "order-service")
          for s in "${SVCS[@]}"; do
            echo "Waiting for EXTERNAL-IP on service/$s ..."
            for i in {1..40}; do
              IP=$(kubectl -n "$NAMESPACE" get svc "$s" -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
              HOST=$(kubectl -n "$NAMESPACE" get svc "$s" -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
              if [ -n "$IP" ] || [ -n "$HOST" ]; then
                echo "::notice title=$s EXTERNAL-IP::${IP:-$HOST}"
                break
              fi
              sleep 15
            done
          done

      - name: Show services (IPs)
        run: kubectl get svc -n "$NAMESPACE" -o wide
